### ISSUE TITLE
Build Error caused by ALIGN macro

### ISSUE THREAD

**Issue by asypost** [LumaTeam/Luma3DS#1970] opened 2023-10-31 14:45 UTC
Luma3DS/sysmodules/pm/source/main.c:19:17: error: expected declaration specifiers or '...' before numeric constant
   19 | static u8 ALIGN(8) processDataBuffer[0x40 * sizeof(ProcessData)] = {0};

**Comment by PabloMK7** [comment] 2023-10-31 15:49
This is probably caused by an update in devkitarm. I'll have to take a look.

**Comment by oreo639** [comment] 2023-10-31 16:15
`ALIGN()` was renamed to `CTR_ALIGN()`.

**Comment by PabloMK7** [comment] 2023-10-31 17:39
Fixed by e2778a4

**Closed by PabloMK7** 2023-10-31 17:39 UTC
