### ISSUE TITLE
black screen when using latest commit

### ISSUE THREAD

**Issue by Cysime** [LumaTeam/Luma3DS#346] opened 2017-01-23 16:32 UTC
i got a problem that when i use the latest release, then i cannot launch Pokemon Sun(cart & cia)
it will work on the latest commit, but when i reboot my New3DSXL(USA),i will black screen when booting.
i FOLLOWED the FAQ about this issue, but it does't work.(NO "svcBreak" in the "loader",just a black screen)

**Comment by TheBigQuack** [comment] 2017-01-23 20:55
same problem cannot boot into any menu reverting to .bak does nothing

**Comment by TheBigQuack** [comment] 2017-01-24 03:04
guess we just have a bricked system lol

**Comment by Cysime** [comment] 2017-01-24 03:09
@TheBigQuack i can boot my system by reverting the bakup, but cannot launch the Pokemon Sun... pretty strange

**Comment by TheBigQuack** [comment] 2017-01-24 03:42
well i had a backup copy of the sd card and that fixed it

**Comment by urherenow** [comment] 2017-01-24 04:23
Special cercumstanses? Region Emulation? I'm imagining a corrupt file caused by an open for reading and failing to close it again

**Comment by TheBigQuack** [comment] 2017-01-24 04:41
once i recovered i tried update again worked once i manually powered off after update

**Comment by Pitel** [comment] 2017-01-24 07:49
Duplicate of #345?

**Comment by TuxSH** [comment] 2017-01-24 08:23
Duplicate

**Closed as completed by TuxSH** 2017-01-24 08:23 UTC
