### ISSUE TITLE
[Feature request] End app process in Rosalina menu?

### ISSUE THREAD

**Issue by RECKZ-RZ** [LumaTeam/Luma3DS#1729] opened 2022-03-21 11:40 UTC
Just something like when you press the start button in some apps in Rosalina to instantly exit out’ve an app

**Comment by Masamune3210** [comment] 2022-03-21 11:49
The problem with adding an option to end a process in the menu is ending something like that doesn't give the game any chance to finish up what it's doing, or the system any chance to go through the normal end game process, which probably leaves the system in a unstable state if other systems are anything to go by

**Comment by TuxSH** [comment] 2022-03-28 20:23
I don't think it's worth implementing it in rosalina menu, but you can do it via gdb.

**Comment by suppai** [comment] 2022-06-05 23:24
Duplicate of #1554.

**Closed by suppai** 2022-06-05 23:24 UTC
