### ISSUE TITLE
3D Splash Support

### ISSUE THREAD

**Issue by Nekukun97** [LumaTeam/Luma3DS#736] opened 2017-07-20 03:06 UTC
¿Support 3D Image Splash? 
Like Menuhax https://gbatemp.net/attachments/tmp_12249-imagedisplay-1401777539-png.29289/

Sorry for my bad english.

**Comment by Margen67** [comment] 2017-07-20 03:26
Duplicate of #458

**Closed as completed** 2017-07-20 15:35 UTC
Labels: duplicate, invalid
