### ISSUE TITLE
Feature Request: Noob proof antiban

### ISSUE THREAD

**Issue by drdeaton** [LumaTeam/Luma3DS#473] opened 2017-05-29 18:04 UTC
Luma3ds is supposed to be noob-proof, right? So why isn't there yet a feature that, instead of forcing us incompetent noob to configure dns, just sends false usage info to nintendo. This would prevent future bans and allow access to eShop and arc13's Open Source Eshop clone, unlike tubehax dns, which also blocks services people like and use.

**Comment by Margen67** [comment] 2017-05-29 18:39
#467 #465

**Comment by TuxSH** [comment] 2017-05-29 18:47
Duplicate of locked issues, locking and closing.

**Closed as completed by TuxSH** 2017-05-29 18:47 UTC
Labels: duplicate, enhancement, rejected
