### ISSUE TITLE
[Feature Request] I want luma to load more cheat instructions

### ISSUE THREAD

**Issue by Rendigga** [LumaTeam/Luma3DS#2048] opened 2024-06-08 11:01 UTC
Although luma can already load a lot of cheat instructions, but my monster Hunter xx has a lot of cheat instructions, so I want luma to display more cheat instructions.please

**Comment by PabloMK7** [comment] 2024-06-08 11:10
Duplicate of #2012

**Closed as not planned by PabloMK7** 2024-06-08 11:10 UTC
