### ISSUE TITLE
DS games crash if H&S has been started before

### ISSUE THREAD

**Issue by r1olo** [LumaTeam/Luma3DS#1273] opened 2019-06-30 16:15 UTC
**System model:** New 2DS XL

**SysNAND version (+emu/redNAND version if applicable):** 11.10.0-43E

**Entrypoint (How/what you're using to boot Luma3DS):** boot9strap

**Luma3DS version:** 10.0

**Luma3DS configuration/options:**

Show NAND or user string in System Settings: (x)

--

**Explanation of the issue:**
If I start H&S, close it, and open any DS game or application (i.e. DS Download Play), I get a crash. It only happens on Luma3DS v10.0. Old 3DS seems unaffected (I tested on both).

**Steps to reproduce:**

1. Open H&S app and close it.

2. Open any DS game/application.

**Dump file:**
[crash_dump_00000000.zip](https://github.com/AuroraWright/Luma3DS/files/3343072/crash_dump_00000000.zip)

**Comment by TuxSH** [comment] 2019-06-30 16:56
Duplicate of #1271

**Closed as completed by TuxSH** 2019-06-30 16:56 UTC
