### ISSUE TITLE
LayeredFS not working with Tomodachi Life USA

### ISSUE THREAD

**Issue by CZ2746isback** [LumaTeam/Luma3DS#1908] opened 2023-06-16 23:06 UTC
**System model:**

[New 2DS XL, New 3DS XL, New 3DS, Old 2DS, **Old 3DS XL**, Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**

[Latest Firmware (SysNAND)]

**Entrypoint (How/what you're using to boot Luma3DS):**

[e.g. **Boot9Strap**/Sighax, etc.]

**Luma3DS version:**

[e.g. v12.0.1]

**Luma3DS configuration/options:**

Default EmuNAND: ( n o )

Screen brightness: ( 4 )

Splash: ( off )

Splash duration: ( 0 )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( x )

Enable game patching: ( x )

Show NAND or user string in System Settings: ( x )

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

--

**Explanation of the issue:**
When I get the patch files, I put them in the correct folders. When I launch the game, the game doesn't start with any patches. When I tested this in other versions of the game, I used the exact same file placement (with a different title ID) and they all worked.

So it appears that there is a problem with Luma3DS with this game. Considering the fact that the mod works on the Japanese, European, and Korean versions (meaning that the patches are not corrupted), and it even works on Citra (meaning that it is not the USA version that's bugged), this is probably a Luma3DS issue.

To be specific, the game does not crash, nor does it throw any errors, but the patches do not start and the game begins without patches.

**Steps to reproduce:**

1. Make any TL mods and patch it for the USA version. (Turn Game Patching on)

2. Start the USA version of Tomodachi Life

**Dump file:**

N/A

**Comment by PabloMK7** [comment] 2023-07-16 22:10
Duplicate of #1900

**Closed as completed by PabloMK7** 2023-07-16 22:10 UTC
