### ISSUE TITLE
is this layeredfs and ips patch bug？

### ISSUE THREAD

**Issue by LittleFIve233** [LumaTeam/Luma3DS#1999] opened 2024-02-22 17:17 UTC
**System model:**
New3DS and New3DS XL

**SysNAND version (+emu/redNAND version if applicable):**
Sysnand: 11.17.0-50J
No Emunand

**Entrypoint (How/what you're using to boot Luma3DS):**
Boot9Strap

**Luma3DS version:**
v13.0.2 stable

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (4)

Splash: ( )

Splash duration: ( )

PIN lock: ( )

New 3DS CPU: (clock)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: (x)

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

--

**Explanation of the issue:**
When using both layeredfs and ips patch for HomeMenu, 3DS will crash even if the romfs folder is empty. Is this a bug? The crash information has been posted.

**Steps to reproduce:**

1.puting ips patch to luma/titles/[homemenuTID]

2.creating "romfs" in luma/titles/[homemenuTID]

Then it crashes when booting

**Dump file:**
[crash_dump_00000000.dmp](https://github.com/LumaTeam/Luma3DS/files/14377189/crash_dump_00000000.dmp)
![IMG20240223010555](https://github.com/LumaTeam/Luma3DS/assets/68946023/65bb1280-e57a-49a8-8891-7a0aa03b9bc3)

**Comment by PabloMK7** [comment] 2024-02-22 17:27
Hello, closing as duplicate of #1954

**Closed as not planned by PabloMK7** 2024-02-22 17:27 UTC
