### ISSUE TITLE
System crashed when start MHX after quit a custom cia

### ISSUE THREAD

**Issue by ITJesse** [LumaTeam/Luma3DS#140] opened 2016-07-02 18:20 UTC
When I run a custom cia like FTP-GMX or BootNTR, and then I can't run MHX.
System will crashed.

But if I run MHX directly, everything is good.

Console: New 3DS JPN with A9LH
System: 11.0.0-33J
Luma3DS branch: developer
Commit: 0eb87df84f2e3877a247596549b8a81599f94594

![img_20160703_021038](https://cloud.githubusercontent.com/assets/3601376/16541883/8688fb76-40c4-11e6-9da8-75a5716eff55.jpg)

[crash_dump_00000002.dmp.zip](https://github.com/AuroraWright/Luma3DS/files/344669/crash_dump_00000002.dmp.zip)

**Comment by ITJesse** [comment] 2016-07-02 18:29
I have update to the latest commit 2d6debddb92aacb0f54e5a1701c5f8866dbaac29, and have no help with this problem.
And now I'm suffering from a randomly boot failed. Console can't boot and freeze on black screen.
When I downgrade to commit 0eb87df it just boot normally.

**Comment by TuxSH** [comment] 2016-07-02 21:55
Did you try closing the homebrew CIA app before launching MHX (just curious).

**Comment by hyln9** [comment] 2016-07-02 22:59
@TuxSH I encountered a similar problem on a New JPN 3DS, and had no luck booting anymore.

**Comment by ITJesse** [comment] 2016-07-03 03:46
@TuxSH not the homebrew CIA.
The homebrew will display some color screen when they start.
But FTP-GMX isn't.

**Comment by TuxSH** [comment] 2016-07-03 08:54
Are you getting the same problem with other homebrew CIAs?

**Comment by TuxSH** [comment] 2016-07-03 10:22
Do you have the same problem with the latest commit on `master` branch?

**Comment by ITJesse** [comment] 2016-07-03 10:36
EasyRPG Player

**Comment by onmyouji** [comment] 2016-07-03 14:28
I think this is a common problem with FTP-GMX.

If you load CIA games or homebrew launcher after exiting FTP-GMX, strange thing will happen. I also had problem when loading Fire Emblem after exiting FTP-GMX.

Check this [GBAtemp post](https://gbatemp.net/threads/release-ftp-gmx-customize-your-ftbrony.410506/page-4#post-6283207) and other posts after that. A user actually found out that the problem is related with libsf2d component of FTP-GMX.

I have no problem after replacing FTP-GMX with ftpd.

**Closed as completed** 2016-09-04 19:35 UTC
Labels: invalid, external issue
