### ISSUE TITLE
[SUGGESTION] Add support for animated/moving GIF splash screens

### ISSUE THREAD

**Issue by Minionguyjpro** [LumaTeam/Luma3DS#1850] opened 2023-03-09 16:25 UTC
Please make it possible to add support for animated/moving splash screens from a GIF file, if possible. I guess it should be possible, as in the Luma3DS configuration things can also move when scrolling through (might be completely different, but should make sense why it should be possible). Because now I want to use a gif that has a fake loading animation, which should move, but it does not work...

**Comment by Masamune3210** [comment] 2023-03-09 22:50
Early boot is very limited, just because a simple config menu can react to presses, that doesn't mean that jumping to gif playback being able to be done should be next thought

**Comment by Minionguyjpro** [comment] 2023-03-10 12:29
Yes, but it might be possible, or in a rate that is low, like 1-5 frames each second or so...

**Comment by PabloMK7** [comment] 2023-07-16 20:57
Duplicate of #459

**Closed as completed by PabloMK7** 2023-07-16 20:57 UTC
Labels: duplicate
