### ISSUE TITLE
Crash if no option is selected in the configuration menu

### ISSUE THREAD

**Issue by BernardoGiordano** [LumaTeam/Luma3DS#173] opened 2016-08-26 06:51 UTC
Tried 6.1 on a CFW 11.0 sysnand, no emunand. I felt like I didn't have to select any option, because I don't have an emunand, so I thought Autoboot Sysnand was superfluous. When I pressed start to save, it remained in that screen, forcing me to shut down.

**Comment by TuxSH** [comment] 2016-08-26 09:27
I deleted my configuration file, and pressed start with no option on. Didn't freeze.

**Comment by BernardoGiordano** [comment] 2016-08-26 12:01
Just tried. I deleted my config.bin . Crash still happens.

Could I add something? I think that whenever a update changes something related to configuration managemente, the cfw should delete the config.bin on first launch to clean everything. I moved from a past version, and I had the first 3 option checked. When I opened the configuration menu on the new update, there were things that I did not select in the past version, like the ones that boot the second emunand instead of the first. Obviously, the stuff I did not select were at the same place of the 3 option that I selected time ago.

**Comment by BernardoGiordano** [comment] 2016-08-26 12:09
Ah, other thing. When this happens and i forcedly shutdown, when I reboot I don't go directly to the config menu (it seems that a config.bin file is still created and found on the SDcard, I assume), but there is no screen init at all. Also a minute later, the screens do not init and obviously the system doesn't start at all. I need to reboot another time, pressing SELECT and select Autoboot Sysnand to get everyhting okay

**Comment by TuxSH** [comment] 2016-08-26 13:19
You're not keeping START held down, are you?

**Comment by BernardoGiordano** [comment] 2016-08-26 16:07
Nope.. just pressed for a moment. I can make a little video about this issue

https://www.youtube.com/watch?v=BtByS6-vzSs

**Comment by TuxSH** [comment] 2016-08-26 16:39
Try the dev branch to see.

**Comment by BernardoGiordano** [comment] 2016-08-26 16:45
It stucked for a while, and then this appeared: 
![image](https://cloud.githubusercontent.com/assets/17624378/18013150/2cd87bd2-6bbd-11e6-81a4-70466fac62ab.jpg)

**Comment by BernardoGiordano** [comment] 2016-08-26 16:46
When I try to reboot instead, I have other values in the registers as this pic says: 
![photo192942266538635388](https://cloud.githubusercontent.com/assets/17624378/18013197/5a12768e-6bbd-11e6-9872-0cb4f8fb1936.jpg)

**Comment by BernardoGiordano** [comment] 2016-08-26 16:47
When I reboot, I have other values in the registers. It goes immediately here: 
![photo192942266538635389](https://cloud.githubusercontent.com/assets/17624378/18013253/8e801c50-6bbd-11e6-9399-77b0a23aaa81.jpg)

**Comment by AuroraWright** [comment] 2016-08-26 23:10
Try again on 6.1.1

**Comment by TuxSH** [comment] 2016-08-26 23:18
Can be a possible duplicate of #169 as well, if you used to have an emunand.

**Comment by BernardoGiordano** [comment] 2016-08-27 06:39
The crash still happens on 6.1.1 . Reading issue #169 I assume this problem is due to a past GW emuNAND (that I used to have before a redNAND). I formatted my SD Card with the 'No emuNAND' option on EmuNAND9. I assume it was a quick format and not a full one

**Comment by TuxSH** [comment] 2016-08-27 18:41
Yeah, that's probably the issue. Try a full format.

**Comment by BernardoGiordano** [comment] 2016-09-01 21:31
Doing the full format between 24hours, I think. Will let you know

**Comment by BernardoGiordano** [comment] 2016-09-04 10:38
Full format done. Issue still persists.  Currently running 6.1.1-7fb17ce5

**Comment by Margen67** [comment] 2016-09-04 11:54
Try looking at the SD card in Disk management in Windows

**Comment by BernardoGiordano** [comment] 2016-09-04 15:14
I made the full format with that tool on Windows

**Comment by AuroraWright** [comment] 2016-09-04 19:45
The issue is surely with your SD card, as I tested the same thing (clean SD, copied the .bin and pressed start on boot), works fine. Maybe windows's tool didn't erase the ncsd header for some reason, if you can do a dd with zeroes from linux

**Closed as completed by AuroraWright** 2016-09-04 19:45 UTC
Labels: invalid
